<?php
  /**
   * iNaturalist observations module
   * Copyright 2014 Projecte Ictineo SCCL (www.projecteictineo.com)
   * aGPLv3
   */

/**
 * Implements hook_menu()
 */
function inat_obs_menu() {
  $items = array();

  //$items['inat/observations'] = array(
    //'title' => t(''),
    //'description' => t(''),
    //'page callback' => '',
    //'access arguments' => '',
    //'menu_name' => 'inaturalist'
    //'type' => MENU_NORMAL_ITEM,
  //);

  $items['inat/projects/%/%'] = array(
    'title' => t('Projects'),
    'description' => t('iNaturalist Observations'),
    'page callback' => 'inat_page_projects',
    'page arguments' => array(2,3),
    //'access arguments' => array('access inaturalist content'),
    'access callback' => TRUE,
    'menu_name' => 'menu-inaturalist',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['inat/projects'] = $items['inat/projects/%/%'];
  $items['inat/projects/%'] = $items['inat/projects/%/%'];

  $items['inat/project/%id'] = array(
    'title' => t('Projects'),
   // 'description' => t('iNaturalist Observations'),
    'page callback' => 'inat_projects',
    'page arguments' => array(2),
    //'access arguments' => array('access inaturalist content'),
    'access callback' => TRUE,
    //'menu_name' => 'menu-inaturalist',
    //'type' => MENU_NORMAL_ITEM,
  );
  $items['inat/observations'] = array(
    'title' => t('Observations'),
    'description' => t('iNaturalist Observations'),
    'page callback' => 'inat_page_observations',
    //'access arguments' => array('access inaturalist content'),
    'access callback' => TRUE,
    'menu_name' => 'menu-inaturalist',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['inat/observations/%obs_id'] = array(
    'title' => t('Observation'),
    //'description' => t('iNaturalist Observations'),
    'page callback' => 'inat_page_observation',
    'page arguments' => array(2),
    //'access arguments' => array('access inaturalist content'),
    'access callback' => TRUE,
    //'menu_name' => 'menu-inaturalist',
    //'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

/**
 * Implements hook_theme
 */
function inat_obs_theme($existing, $type, $theme, $path) {
  return array( 
    
   
      'inat_projects_general' => array(
      'variables' => array('projects' => NULL),
      'template' => 'projects_general',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
      'inat_project' => array(
      'variables' => array('projects' => NULL),
      'template' => 'project',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
       'inat_projects_list' => array(
      'variables' => array('projects' => NULL),
      'template' => 'projects_list',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
      'inat_observations_general' => array(
      'variables' => array('observations' => NULL),
      'template' => 'observations_general',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
    'inat_observation_list' => array(
      'variables' => array('observation' => NULL),
      'template' => 'observation_list',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
    'inat_observation' => array(
      'variables' => array('observation' => NULL),
      'template' => 'observation',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    ),
     'inat_map' => array(
      'variables' => array('observations' => NULL),
      'template' => 'map',
      'path' => drupal_get_path('module', 'inat_obs') . '/theme',
    )
 
  );
}

/**
 * Implements hook_preprocess()
 */
function inat_obs_preprocess_inat_observations_general(&$var) {

  foreach($var['observations'] as $id => $obs) {
    $var['observations'][$id] = theme('inat_observation_list', array('observation' => $obs));
  }
  drupal_add_css(drupal_get_path('module', 'inat_obs') . '/css/observations.css');
}
function inat_obs_preprocess_inat_projects_general(&$var){
  foreach($var['projects'] as $id => $obs) {
    $var['projects'][$id] = theme('inat_projects_list', array('projects' => $obs));
  }
  drupal_add_css(drupal_get_path('module', 'inat_obs') . '/css/projects.css');

}

/**
 * helper functions
 */

/**
 * Willcard processors
 */

function project_id_load($id2) {

  return $id2;
}

function obs_id_load($id) {
  // TODO limit the allowed values
  //if(is_int($id)) {
    //return $id;
  //} else {
    //return '';
  //}
  return $id;
}


/**
 * Hook menu page callbacks to call iNaturalist API
 * http://www.slideshare.net/jkopel/pnwds-api
 * http://www.inaturalist.org/pages/api+reference
 */


function inat_page_projects($featured = TRUE, $page = NULL) {
  $verb = 'projects.json';
  $query = array();
  if($featured == 'featured') {
    $query = array('featured' => 'true');
  }
  if(is_numeric($page)) {
    $query += array('page' => $page);
  }elseif (is_numeric($page)) {
    $query += array('page' => $featured);
  }
  $options = array('query' => $query, 'https' => FALSE);
  $url = url(variable_get('inat_base_url','http://www.inaturalist.org') . '/' . $verb, $options);
  $options = array('method' => 'GET');
  dsm($url);
  $result = drupal_http_request($url, $options);
  $json = drupal_json_decode($result->data);
  //return var_export($json);
  return  theme('inat_projects_general', array('projects' => $json));
 
}

function inat_projects($id) {
  print('Estem a inat_projects amb id2=' . $id);
  print_r($id);
  print('<hr />');
  $verb = 'projects/'.$id2.'.json';
  
  $query = array();
  $options = array('query' => $query, 'https' => FALSE);
  $url = url(variable_get('inat_base_url','http://www.inaturalist.org') . '/' . $verb, $options);
  $options = array('method' => 'GET');

  $result = drupal_http_request($url, $options);
  $json = drupal_json_decode($result->data);
  print_r($result);
  return  theme('inat_project', array('projects' => $json));
 
}

function inat_page_observations() {
  $verb = 'observations.json';
  $query = array('per_page' => '40', 'order_by' => 'observed_on');
  $options = array('query' => $query, 'https' => FALSE);
  $url = url(variable_get('inat_base_url','http://www.inaturalist.org') . '/' . $verb, $options);
  $options = array('method' => 'GET');
  $result = drupal_http_request($url, $options);
  $json = drupal_json_decode($result->data);
  
  //return var_export($json);
  return theme('inat_map', array('observations' => $json)) . theme('inat_observations_general', array('observations' => $json));
}
function inat_page_observation($id) {
  dsm($id);
  $verb = 'observations/'.$id.'.json';
  $query = array();
  $options = array('query' => $query, 'https' => FALSE);
  $url = url(variable_get('inat_base_url','http://www.inaturalist.org') . '/' . $verb, $options);
  dsm($url);
  $options = array('method' => 'GET');
  $result = drupal_http_request($url, $options);
  $json = drupal_json_decode($result->data);
  dsm($json);

  return theme('inat_observation', array('observation' => $json));
}
