<?php
  /**
   * iNaturalist login module
   * Copyright 2014 Projecte Ictineo SCCL (www.projecteictineo.com)
   * aGPLv3
   */

/**
 * Implements hook_block_info()
 */
function inat_login_block_info() {
  $blocks['inat_login'] = array (
    'info' => t('iNaturalist login block'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['inat_usrinfo'] = array (
    'info' => t('iNaturalist logged user information'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 * https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_view/7
 */
function inat_login_block_view($delta = '') {
  switch($delta) {
    case 'inat_login':
      $block['subject'] = t('iNaturalist login');
      $block['content'] = drupal_get_form('inat_login_login_form');
    break;
    case 'inat_usrinfo':
      $block['subject'] = t('iNaturalist user information');
      $block['content'] = inat_login_usrinfo_content($delta);
    break;
  }
  return $block;
}


/**
 * Helper functions [no hooks]
 */

/**
 * this function returns string o renderable array
 * with the block content for inat_login block
 */
function inat_login_login_form($form_state) {
  // Settings to pass into javascript file with the login url
  //drupal_add_js(array('sso_moodle' =>array('login_url' =>variable_get('moodle_login_url',''))), 'setting');

  $form['#method'] = 'post';
  $form['#attributes'] = array( 'id' => 'inat_login_login_form' );
  $form['user_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Username or email'),
    '#size' => 30,
    '#required' => TRUE,
  );
  $form['user_password'] = array(
    '#type' => 'password',
    '#title' => t('password'),
    '#size' => 30,
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Login'),
  );
  return $form;
}

function inat_login_login_form_submit($form, &$form_state){

  // Initial psuedo-code, sending an HTTP petiton directly to inat framework
  // peticio_HTML=( $form_state['values']['user_email'], $form_state['values']['user_password'];
  // send_petition_to(url,peticio_HTML);
  
 //First of all, we extract from de form the values, and we construct an a formated array to make de petition
 //$verb = it's de place where we are asking, in this example de session action is who proces login Inat form
    drupal_set_message(t('The form has been submitted.'));
   $verb = 'session';
   $user_email = $form_state['values']['user_email'];
   $user_password = $form_state['values']['user_password'];
   $query = array('user_email' => $user_email, 'user_password' => $user_password);
   $options = array('query' => $query, 'https' => FALSE);
 //Once we have de data ready, we should construct our url and call the function drupal_http_request 
   $url = url(variable_get('inat_base_url','http://www.inaturalist.org') . '/' . $verb, $options);
   $options = array('method' => 'POST');
   $result = drupal_http_request($url, $options);
   
   dsm($json); 
// we get de data in json format.
   $json = drupal_json_decode($result->data);
  //return var_export($json);
  return theme('inat_observations', array('observations' => $json)); 
   

}


/**
 * this function returns string o renderable array
 * with the block content for inat_usrinfo block
 */
function inat_login_usrinfo_content($delta) {
  return 'contingut dumi pel bloc de informacio de lusuari';
}
